#!/bin/bash

if [ "$#" -lt 2 ]; then
  echo "Usage: $(basename $0) /path/to/etcd.js /path/to/configdir /path/to/logfile" >&2
  exit 1
fi

ETCDJS=$1
CONFIGDIR=$2
LOGFILE=$3


NODE=$(which nodejs 2>/dev/null|| which node 2>/dev/null)

if ! [ -x "$NODE" ]; then
  echo "Unable to run node  '${NODE}' cannot be executed" >&2
  exit 255
fi

if ! [ -r "$ETCDJS" ]; then
  echo "Unable to read '$ETCDJS' - file is either missing or unreadable"
  exit 255
fi

if ! [ -r "$CONFIGDIR" ]; then
  echo "Unable to read '$CONFIGDIR' - file is either missing or unreadable"
  exit 255
fi

exec 3>&2
if [ -n "$LOGFILE" ]; then
  exec 1>>$LOGFILE
  exec 2>>$LOGFILE
fi

echo "Running $CONFIGDIR $NODE $ETCDJS"
exec $NODE $ETCDJS $CONFIGDIR

echo "Unable to execute ${CONFIGDIR} ${NODE} ${ETCDJS}!" >&3
exit 1
